- name: Deploy SciCalc Docker container
  hosts: localhost
  become: no

  tasks:
    # 1. Ensure python3-docker system package is installed (safe on Ubuntu/Debian)
    - name: Ensure python3-docker system package is installed
      apt:
        name: python3-docker
        state: present
      when: ansible_facts['pkg_mgr'] == 'apt'

    # 2. Deploy and manage scientific-calculator container
    - name: Deploy and manage scientific-calculator container from Docker Hub
      community.docker.docker_container:
        name: calc-app2
        image: "areen9295/calc-app2:{{ docker_image_tag | default('latest') }}"
        state: started
        pull: yes
        recreate: yes
        ports:
          - "9000:80"
        restart_policy: always
