- name: Deploy SciCalc Docker container
  hosts: local
  become: no

  tasks:
    - name: Ensure Python 'docker' is there
      ansible.builtin.pip:
        name: docker
        state: present
     
    # 2. Deploy and manage scientific-calculator container
    - name: Deploy and manage scientific-calculator container from Docker Hub
      community.docker.docker_container:
        name: calc-app2
        image: areen9295/calc-app2:latest
        state: started
        pull: yes
        recreate: yes
        ports:
          - "9000:80"
        restart_policy: always
